'use client'

// GitHub PAT 连接与项目推送（全部在浏览器直调 GitHub API，PAT 不出本地）
import type { AuthUser } from '@/components/LoginModal'

const KEY = 'jlcoding:github'

export interface GithubConnection {
  token: string
  login: string
  avatar: string
}

export function loadGithub(): GithubConnection | null {
  if (typeof window === 'undefined') return null
  try {
    const raw = localStorage.getItem(KEY)
    return raw ? JSON.parse(raw) : null
  } catch {
    return null
  }
}

export function saveGithub(conn: GithubConnection): void {
  localStorage.setItem(KEY, JSON.stringify(conn))
}

export function clearGithub(): void {
  localStorage.removeItem(KEY)
}

// 验证 PAT 并返回连接信息
export async function verifyGithubPat(pat: string): Promise<GithubConnection> {
  const res = await fetch('https://api.github.com/user', {
    headers: { Authorization: `Bearer ${pat}`, 'User-Agent': 'jlcoding' },
  })
  if (!res.ok) {
    throw new Error(res.status === 401 ? 'Token 无效或已过期' : `GitHub 返回 ${res.status}`)
  }
  const user = await res.json()
  return { token: pat, login: user.login, avatar: user.avatar_url }
}

// 推送项目文件到新仓库：建仓 → 逐文件提交
export async function pushProjectToGithub(
  conn: GithubConnection,
  projectName: string,
  files: { path: string; content: string }[]
): Promise<string> {
  const headers = {
    Authorization: `Bearer ${conn.token}`,
    'User-Agent': 'jlcoding',
    'Content-Type': 'application/json',
  }
  // 1. 建仓库（失败时尝试用现有同名仓库）
  const repoName = `jlcoding-${projectName.replace(/[^\w\u4e00-\u9fa5-]+/g, '-').slice(0, 30).toLowerCase() || 'app'}-${Date.now().toString(36).slice(-4)}`
  const createRes = await fetch('https://api.github.com/user/repos', {
    method: 'POST',
    headers,
    body: JSON.stringify({ name: repoName, description: 'Generated by jlCoding', private: false, auto_init: true }),
  })
  if (!createRes.ok && createRes.status !== 422) {
    throw new Error(`创建仓库失败（${createRes.status}）`)
  }
  // 2. 逐文件提交（contents API）
  for (const file of files) {
    const putRes = await fetch(
      `https://api.github.com/repos/${conn.login}/${repoName}/contents/${encodeURIComponent(file.path)}`,
      {
        method: 'PUT',
        headers,
        body: JSON.stringify({
          message: `jlCoding: add ${file.path}`,
          content: btoa(unescape(encodeURIComponent(file.content))),
        }),
      }
    )
    if (!putRes.ok) {
      // auto_init 已存在同名文件（README）等非致命错误忽略，其余中断
      if (putRes.status !== 422) {
        throw new Error(`提交 ${file.path} 失败（${putRes.status}）`)
      }
    }
  }
  return `https://github.com/${conn.login}/${repoName}`
}

export type { AuthUser }
